### ISSUE TITLE
intense-wallet-vpn-rpc.[port].login file created with 0x400. What about 0x600 ?

### ISSUE THREAD

**Issue by zib92130** [letheanVPN/blockchain#112]
No sure this is a problem indeed. I've just rebooted my server and cannot restart RPC because that file cannot be overwritten. It is well said in the debug logs...
Maybe there's a way to properly shutdown RPC to get the file removed ? 
Nevertheless I don't see the reason why not to allow Write for the owner.
You know better, you decide !  :-)

**Comment by readon1y** [comment]
when the server is restarted, cron launches lethean-wallet-vpn-rpc, but it dies with an error

2018-10-19 19: 26: 40.894 7f9dfdb29740 ERROR wallet.vpn.rpc src/wallet/wallet_vpn_rpc_server.cpp: 175 Failed to create file lethean-wallet-vpn-rpc.14660.login. Check permissions or remove file
2018-10-19 19: 26: 40.894 7f9dfdb29740 ERROR wallet.vpn.rpc src/wallet/wallet_vpn_rpc_server.cpp: 703 Failed to initialize wallet rpc server

why do you need it? I do not understand.
it turns out the wallet can not create a file, since it already exists and it has rights

-r-------- 1 vpnuser vpnuser 21 Oct 19 20:31 lethean-wallet-vpn-rpc.14660.login

with such rights it is impossible to create a file and we are offered to delete it in order to create a new file.
and when the wallet does not work, then itnsdispatcher dies with an error

ERROR: root: No connection to wallet. Exiting

if lethean-wallet-vpn-rpc and itnsdispatcher do not work, then when we connect to the node, we get error 503 and we cannot connect, and the coins will already go away.
I found such a way out. in cron the first line I added

@reboot unlink /home/vpnuser/lethean-wallet-vpn-rpc.14660.login

this will first remove the file lethean-wallet-vpn-rpc.14660.login, and then the wallet and itnsdispatcher will start well

perhaps for this reason we have many non-working nodes. since after a reboot, it is impossible to run lethean-wallet-vpn-rpc and itnsdispatcher

**Comment by iedemam** [comment]
Thanks for bringing attention to this. I've bumped it up for review for this release instead of the next one.

**Comment by limosek** [comment]
Fixed in https://github.com/LetheanMovement/lethean/commit/62ffbef0802b27f0841b18d6e9c273dae6e3ec0d
